name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Protoc
        uses: abelfodil/protoc-action@v1

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Script
        env:
          DOCKERHUB_OWNER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: export GOPATH=$HOME/go; .github/script.sh