name: CI

on:
  push:
    branches:
      - master
      - 'add-ci'
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Use Node
          uses: actions/setup-node@v1
          with:
            node-version: 12.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build & Push Docker Images
        env:
          DOCKERHUB_OWNER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: make